# -*- coding: utf-8 -*-
"""Sample_Level_GEM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOj0MjUP9iS2phGNHG26XwzYALvZALuF
"""

!pip install cobra mygene optlang highspy -q --upgrade
!apt-get install -y glpk-utils -q

import cobra
import pickle
import os
import numpy as np
from cobra.flux_analysis import pfba, flux_variability_analysis
from cobra.util.solver import linear_reaction_coefficients
from optlang.symbolics import Zero
import sys
import mygene
import pandas as pd
from collections import Counter
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import ast
from cobra.core.gene import GPR
from ast import And, Or
import highspy
print("highspy OK")

import optlang
print(optlang.available_solvers)

pd.set_option("display.max_colwidth", 55)
pd.set_option("display.width",        130)

cobra.Configuration().solver = "hybrid"

from google.colab import drive
drive.mount('/content/drive')

"""Load GEM"""

GEM_PATH = "/content/drive/MyDrive/Human-GEM.xml"
project_folder = "/content/drive/MyDrive/GEM Results/Ker1/"

model = cobra.io.read_sbml_model(GEM_PATH)
model.solver = "hybrid"

print("Model loaded:", model.name)
print("Reactions:",    len(model.reactions))
print("Metabolites:",  len(model.metabolites))
print("Genes:",        len(model.genes))
print(f"Solver: {model.solver.interface.__name__}")

# Baseline FBA, used only as a sanity-check: GIMME will re-run FBA per model
baseline_solution = model.optimize()
BASELINE_BIOMASS = baseline_solution.objective_value
print(f"Baseline biomass (unconstrained): {BASELINE_BIOMASS:.4f}")

"""Load Input Data"""

DATA_PATH = "/content/drive/MyDrive/gem_input_data7.pkl"

with open(DATA_PATH, "rb") as f:
    gem_data = pickle.load(f)

metadata        = gem_data["metadata"]
nmr             = gem_data["nmr"]
microbiome      = gem_data["microbiome"]
pathways        = gem_data["pathways"]
mean_expr       = gem_data["mean_expr"]
mean_expr_high  = gem_data["mean_expr_high"]
mean_expr_low   = gem_data["mean_expr_low"]
metabolite_map  = gem_data["metabolite_map"]
gem_metabolites = gem_data["gem_metabolites"]
common_ids      = gem_data["common_ids"]

print("Loaded GEM input data.")
print("Samples:",                    len(common_ids))
print("Metabolites for constraints:", gem_metabolites)
print("Metadata shape:",  metadata.shape)
print("NMR shape:",        nmr.shape)
print("Mean expr shape:",  mean_expr.shape)

# Verify the mapping integration
print("Mapped Metabolites to Model IDs:")
for name, mam_id in gem_data['metabolite_map'].items():
    try:
        # Check if the ID exists in your loaded model
        met = model.metabolites.get_by_id(mam_id)
        print(f"Verified: {name} as {mam_id}")
    except KeyError:
        print(f"Warning: {mam_id} ({name}) not found in loaded model.")

"""Exchange Reaction ID Map for Constraining Models"""

# Human_GEM Exchange Reaction IDs - for applying uptake/secretion constraints
# Exchange mapping dictionary for each metabolite and its corresponding Human_GEM ID
# Use these IDs to add constraints
exchange_map = {
    "Glucose": "MAR09034", "Arginine": "MAR09066", "Urea": "MAR09081",
    "Lactic acid": "MAR09135", "Succinic acid": "MAR09415", "Proline": "MAR09068",
    "Lysine": "MAR09041", "Alanine": "MAR09061", "Tyrosine": "MAR09064",
    "Isoleucine": "MAR09039", "Tryptophan": "MAR09045", "Histidine": "MAR09040",
    "Ammonia": "MAR09074", "Protons": "MAR09048",

    "Valine": "MAR09046", "Leucine": "MAR09042", "Phenylalanine": "MAR09043",
    "Threonine": "MAR09044", "Methionine": "MAR09047", "Serine": "MAR09069",
    "Glycine": "MAR09065", "Aspartic acid": "MAR09062", "Glutamic acid": "MAR09063",
    "Asparagine": "MAR09067", "Glutamine": "MAR09070", "Cysteine": "MAR09071",
    "Ornithine": "MAR09080", "Citrulline": "MAR09078",
    "Pyroglutamic acid": "MAR09072",
    "Formic acid":      "MAR09126",
    "Hypoxanthine?":    "MAR09241",
    "Urocanic acid":    "MAR09082",
    "Maleic acid":      "MAR09136",
    "Pimelic (or suberic) acid": "MAR09121",

    "Citric acid": "MAR09124", "Fumaric acid": "MAR09127", "Malic acid": "MAR09137",
    "Pyruvic acid": "MAR09140", "Acetoacetic acid": "MAR09109", "Acetic acid": "MAR09123",
    "Creatinine": "MAR09075", "Creatine": "MAR09076", "Choline": "MAR09260",
    "Taurine": "MAR09073", "myo-Inositol": "MAR09231", "Glycerol": "MAR09132"
}

# Define directions: Most things are taken up; byproduct/waste are secreted.
# If a metabolite isn't here, it defaults to 'uptake' in the logic below.
METABOLITE_DIRECTION = {
    "Lactic acid": "secreted",
    "Succinic acid": "secreted",
    "Urea": "secreted",
    "Ammonia": "secreted",
    "Creatinine": "secreted",
    "Acetic acid": "secreted",
    "Protons": "secreted"
}

# Remove the 'Unknowns' and contaminants to clean up the warnings
to_remove = ["Unknown 1", "Unknown 2", "Unknown 3", "Unknown 4", "Epsilon-Caprolactam"]
for item in to_remove:
    if item in exchange_map:
        del exchange_map[item]

print(f"Total mapped metabolites: {len(exchange_map)}")



def get_exchange_id(model, mam_id):
    """Finds the true exchange/boundary reaction for a metabolite MAM ID."""
    try:
        met = model.metabolites.get_by_id(mam_id)
    except KeyError:
        return None
    exchanges = [r for r in met.reactions if len(r.metabolites) == 1]
    return exchanges[0].id if exchanges else None

  # Now re-run your Pass 1 with this updated function
# exchange_map already populated above with hand-curated values -- don't reset it
for nmr_name, mam_id in gem_data['metabolite_map'].items():
    if nmr_name in exchange_map:
        continue  # already have a verified ID
    ex_id = get_exchange_id(model, mam_id)
    if ex_id:
        exchange_map[nmr_name] = ex_id
        print(f"Linked: {nmr_name} → {ex_id}")
    else:
        print(f"No exchange found for: {nmr_name} ({mam_id})")

def find_exchange_reaction(model, metabolite_name):
    """Searches for an exchange reaction matching the metabolite name."""
    for met in model.metabolites:
        # Check if metabolite name matches NMR name (case-insensitive)
        if metabolite_name.lower() in met.name.lower():
            # Find the exchange reaction for this metabolite
            exchanges = [r for r in met.reactions if len(r.metabolites) == 1]
            if exchanges:
                return exchanges[0].id
    return None

# Update map based on your specific NMR columns
for met_name in nmr.columns:
    if met_name not in exchange_map:
        found_id = find_exchange_reaction(model, met_name)
        if found_id:
            exchange_map[met_name] = found_id
            print(f"Linked (Fuzzy): {met_name} -> {found_id}")
        else:
            print(f"Warning: Could not find ID for {met_name}")

print(len(exchange_map))
print(len(gem_data['metabolite_map']))
print(exchange_map)

"""Map Gene Symbols to Ensembl IDs"""

mg = mygene.MyGeneInfo()
symbols = list(mean_expr.index)
mapping = mg.querymany(symbols, scopes='symbol', fields='ensembl.gene', species='human')
symbol_to_ens = {}
for entry in mapping:
    if 'notfound' in entry and entry['notfound']:
        continue
    if 'ensembl' not in entry:
        continue
    ens = entry['ensembl']
    if isinstance(ens, list):
        ens = ens[0]
    if isinstance(ens, dict) and 'gene' in ens:
        symbol_to_ens[entry['query']] = ens['gene']

print(f"Mapped {len(symbol_to_ens)} gene symbols to Ensembl IDs.")

"""Gene ID Conversion (used to map sample-level expression to Ensembl)"""

def convert_expr_to_ensembl(expr_df, mapping_dict):
    expr_df = expr_df.loc[expr_df.index.intersection(mapping_dict.keys())].copy()
    expr_df.index = expr_df.index.map(mapping_dict)
    expr_df = expr_df.groupby(expr_df.index).mean()
    return expr_df

"""GPR_Aware GIMME Weighting"""

def evaluate_gpr(gpr_node, expr_lookup):
    """
    Recursively evaluate a COBRApy GPR expression tree.
    AND nodes -> min (enzyme complex: all subunits needed)
    OR  nodes -> max (isozymes: any isoform sufficient)
    """
    if gpr_node is None:
        return None

    if hasattr(gpr_node, 'id'):
        return expr_lookup.get(gpr_node.id, None)
    if hasattr(gpr_node, 'name'):
        return expr_lookup.get(gpr_node.name, None)

    if hasattr(gpr_node, 'args') and isinstance(gpr_node, ast.BoolOp) and isinstance(gpr_node.op, ast.And):
        child_vals = [evaluate_gpr(child, expr_lookup) for child in gpr_node.args]
        child_vals = [v for v in child_vals if v is not None]
        return min(child_vals) if child_vals else None

    if hasattr(gpr_node, 'args') and isinstance(gpr_node, ast.BoolOp) and isinstance(gpr_node.op, ast.Or):
        child_vals = [evaluate_gpr(child, expr_lookup) for child in gpr_node.args]
        child_vals = [v for v in child_vals if v is not None]
        return max(child_vals) if child_vals else None

    if hasattr(gpr_node, 'body'):
        return evaluate_gpr(gpr_node.body, expr_lookup)

    return None


def build_reaction_weights(model, expr_series, threshold=None):
    """
    weight = max(0, threshold - gpr_expression)
    0.0  -> reaction supported by expression (no GIMME penalty)
    >0.0 -> penalised proportionally to expression deficit
    """
    nonzero_expr = expr_series[expr_series > 0]
    if threshold is None:
        threshold = float(np.percentile(nonzero_expr, 10)) if len(nonzero_expr) > 0 else 0.1

    expr_lookup = expr_series.to_dict()
    weights = {}

    for rxn in model.reactions:
        if not rxn.gene_reaction_rule or rxn.gene_reaction_rule.strip() == '':
            weights[rxn.id] = 0.0
            continue

        try:
            tree = ast.parse(rxn.gene_reaction_rule, mode='eval')
            rxn_expr = evaluate_gpr(tree, expr_lookup)
        except Exception:
            rxn_expr = None

        if rxn_expr is None:
            weights[rxn.id] = float(threshold)
        else:
            weights[rxn.id] = max(0.0, threshold - float(rxn_expr))

    return weights, threshold

"""Cleanup Leftover Demand Reactions on Base Model"""

dms_to_remove = [r.id for r in model.reactions if r.id.startswith("DM_")]
if dms_to_remove:
    model.remove_reactions(dms_to_remove)
    print(f"Cleaned {len(dms_to_remove)} leftover demand reactions.")

"""Medium/Metabolite Constraints"""

ESSENTIAL_OPEN_EXCHANGES = {
    "MAR09048": (-1000.0, 1000.0),  # Protons
    "MAR09150": (-1000.0, 1000.0),  # H2O
    "MAR09155": (-1000.0, 1000.0),  # O2
    "MAR09079": (-1000.0, 1000.0),  # Inorganic phosphate (Pi)
    "MAR09153": (-1000.0, 1000.0),  # CO2
    "MAR09143": (-1000.0, 1000.0),  # Sulphate
    "MAR09074": (-1000.0, 1000.0),  # Ammonia
    "MAR09047": (-1.0, 1000.0),     # Methionine
    "MAR09065": (-1.0, 1000.0),     # Glycine
    "MAR09070": (-1.0, 1000.0),     # Glutamine
    "MAR09071": (-1.0, 1000.0),     # Cysteine
    "MAR09147": (-1.0, 1000.0),     # Magnesium
    "MAR09145": (-1.0, 1000.0),     # Potassium
    "MAR09141": (-1.0, 1000.0),     # Calcium
    "MAR09146": (-1.0, 1000.0),     # Sodium
    "MAR09144": (-1.0, 1000.0),     # Chloride
    "MAR09142": (-0.01, 1000.0),    # Iron (Fe2+)
    "MAR09149": (-0.01, 1000.0),    # Manganese
    "MAR09148": (-0.01, 1000.0),    # Cu2+
    "MAR09151": (-0.01, 1000.0),    # Zn2+
    "MAR09100": (-0.01, 1000.0),    # Biotin
    "MAR09107": (-0.01, 1000.0),    # Pantothenate
    "MAR09101": (-0.01, 1000.0),    # Folate (B9)
    "MAR09108": (-0.01, 1000.0),    # Riboflavin (B2)
    "MAR09105": (-0.01, 1000.0),    # Nicotinate (B3)
    "MAR09104": (-0.01, 1000.0),    # Pyridoxine (B6)
    "MAR09109": (-0.01, 1000.0),    # Thiamine (B1)
    "MAR09132": (-0.1, 1000.0),     # Glycerol
    "MAR09260": (-0.1, 1000.0),     # Choline
    "MAR09231": (-0.1, 1000.0),     # myo-Inositol
    "MAR09228": (-0.01, 1000.0),    # Cholesterol
    "MAR09115": (-0.01, 1000.0),    # Linoleic acid
    "MAR09103": (-0.01, 1000.0),    # Vitamin B12
    "MAR09083": (-1000.0, 1000.0),  # Bicarbonate
}

TRICKLE_VALUE = -0.01  # Small "background" flux allowed for unmeasured metabolites


def medium_relaxed(model_copy):
    n_relaxed = 0
    for rxn in model_copy.boundary:
        if rxn.lower_bound < 0:
            rxn.lower_bound = TRICKLE_VALUE
            n_relaxed += 1
    return n_relaxed


def apply_metabolite_constraints(base_model, nmr_profile, exchange_map,
                                  metabolite_direction, scale=None):
    if scale is None:
        scale = SCALE

    m = base_model.copy()

    to_remove = [r.id for r in m.reactions if r.id.startswith("DM_") or r.id.startswith("TEST_")]
    if to_remove:
        m.remove_reactions(to_remove)

    n_relaxed = medium_relaxed(m)
    print(f"  Relaxed {n_relaxed} exchange reactions (trickle set to {TRICKLE_VALUE}).")

    for rxn_id, (lb, ub) in ESSENTIAL_OPEN_EXCHANGES.items():
        try:
            rxn = m.reactions.get_by_id(rxn_id)
            rxn.lower_bound = lb
            rxn.upper_bound = ub
        except KeyError:
            continue

    for met_name, rxn_id in exchange_map.items():
        if met_name not in nmr_profile.index:
            continue
        level = float(nmr_profile[met_name])
        level = max(0.0, level)
        flux = scale * level
        rxn = m.reactions.get_by_id(rxn_id)
        direction = metabolite_direction.get(met_name, "uptake")

        if direction == "uptake":
            rxn.lower_bound = -flux
        else:
            rxn.upper_bound = flux
            rxn.lower_bound = 0.0

    return m

"""Skin pH Context"""

def apply_environmental_context(model, condition_type):
    """
    High SA -> pH 6.13 (more alkaline) -> easier proton efflux
    Low SA  -> pH 5.13 (more acidic)   -> harder proton efflux
    """
    m = model.copy()
    h_plus_exchange = "MAR09048"
    if condition_type == 'high':
        m.reactions.get_by_id(h_plus_exchange).lower_bound = -1000.0
    elif condition_type == 'low':
        m.reactions.get_by_id(h_plus_exchange).lower_bound = -400.0
    return m

"""Metabolic Task Validation"""

METABOLIC_TASKS_BY_CT = {
    "KER1": [
        ("Biomass production",          "MAR13082", 0.01),
        ("Glucose uptake",               "MAR09034", None),
        ("ATP production (via ATPM)",    "MAR03964", 0.01),
        ("Fatty acid synthesis",         "MAR00010", None),
        ("Amino acid catabolism (Arg)",  "MAR04209", None),
    ],
    "T CELL": [
        ("Biomass production (Proliferation)", "MAR13082", 0.01),
        ("Glucose uptake (Glycolytic engine)",  "MAR09034", None),
        ("ATP production (via ATPM)",           "MAR03964", 0.01),
        ("Lactate secretion (Aerobic Glyco)",   "MAR09135", None),
        ("Glutamine uptake (Glutaminolysis)",   "MAR09070", None),
        ("TCA Cycle Capacity (SDH reaction)",   "MAR04360", None),
    ],
}


def run_metabolic_tasks(constrained_model, condition_label, tasks):
    print(f"\n--- Metabolic Task Validation: {condition_label} ---")
    all_passed = True
    for task_name, rxn_id, min_flux in tasks:
        try:
            rxn = constrained_model.reactions.get_by_id(rxn_id)
        except KeyError:
            print(f"  [SKIP] {task_name:<40} -- reaction {rxn_id} not in model")
            continue

        with constrained_model as test_model:
            test_model.objective = rxn_id
            sol = test_model.optimize()
            achieved = sol.objective_value if sol.status == 'optimal' else 0.0

        passed = (achieved >= min_flux) if min_flux is not None else (achieved > 1e-9)
        status = "PASS" if passed else "FAIL"
        if not passed:
            all_passed = False
        print(f"  [{status}] {task_name:<40} max flux = {achieved:.4f}")

    print("  All tasks passed." if all_passed else "  One or more tasks FAILED.")
    return all_passed

"""GIMME"""

def run_gimme(model, reaction_weights, fraction_of_optimum=0.9):
    rxn_map = {r.id: r for r in model.reactions}

    coeffs = model.objective.get_linear_coefficients(model.variables)
    biomass_rxn = next((r for r in model.reactions
                        if r.forward_variable in coeffs or r.reverse_variable in coeffs), None)
    if not biomass_rxn:
        raise ValueError("Could not identify the objective reaction.")

    original_objective = model.objective
    original_lb = biomass_rxn.lower_bound

    try:
        fba_sol = model.optimize()
        if fba_sol.status != 'optimal':
            return None, None

        max_biomass = fba_sol.objective_value
        biomass_rxn.lower_bound = max_biomass * fraction_of_optimum

        objective_dict = {}
        for key, weight in reaction_weights.items():
            r_id = key.id if hasattr(key, 'id') else str(key)
            if weight > 0 and r_id in rxn_map:
                rxn = rxn_map[r_id]
                objective_dict[rxn.forward_variable] = weight
                objective_dict[rxn.reverse_variable] = weight

        model.objective = model.problem.Objective(Zero, direction="min")
        model.objective.set_linear_coefficients(objective_dict)

        gimme_sol = model.optimize()
        if gimme_sol.status != 'optimal':
            print(f"  WARNING: GIMME-weighted solve status='{gimme_sol.status}' -- treating as failed.")
            return None, max_biomass

        return gimme_sol, max_biomass

    finally:
        biomass_rxn.lower_bound = original_lb
        model.objective = original_objective

"""Post-Processing Functions"""

def open_nutrient_doors(model):
    for reaction in model.exchanges:
        if reaction.lower_bound == 0:
            reaction.lower_bound = -10.0
    print(f"Doors opened for {model.id}")


def cleanup(model):
    seen_ids = set()
    to_keep = []
    removed_duplicates = 0
    removed_dms = 0
    for rxn in model.reactions:
        if rxn.id.startswith("DM_"):
            removed_dms += 1
            continue
        if rxn.id in seen_ids:
            removed_duplicates += 1
            continue
        seen_ids.add(rxn.id)
        to_keep.append(rxn)

    new_model = cobra.Model(model.id)
    new_model.add_reactions(to_keep)

    if isinstance(model.objective, cobra.Reaction):
        new_model.objective = model.objective.id
    else:
        new_model.objective = model.objective

    print(f"  Removed {removed_dms} DM reactions.")
    print(f"  Removed {removed_duplicates} duplicate IDs.")

    new_model.solver = 'hybrid'
    growth = new_model.slim_optimize()
    if growth <= 0:
        print(f"  WARNING: Model is non-functional after cleanup! (Growth: {growth:.4f})")
    else:
        print(f"  Model healthy! Growth: {growth:.4f}")
    return new_model


def run_safe_fva(model, reaction_list, fixed_growth_rate):
    results = {}
    total = len(reaction_list)
    print(f"Starting Safe FVA on {total} reactions at fixed growth {fixed_growth_rate}...")

    coeffs = model.objective.get_linear_coefficients(model.variables)
    biomass_rxn = next((r for r in model.reactions
                        if r.forward_variable in coeffs or r.reverse_variable in coeffs), None)
    if not biomass_rxn:
        raise ValueError("Biomass reaction not found in objective.")

    with model:
        biomass_rxn.lower_bound = fixed_growth_rate
        biomass_rxn.upper_bound = fixed_growth_rate

        rxn_map = {rid: model.reactions.get_by_id(rid) for rid in reaction_list if rid in model.reactions}
        for i, rid in enumerate(rxn_map.keys()):
            rxn = rxn_map[rid]
            model.objective = rxn
            model.objective_direction = 'min'
            f_min = model.slim_optimize()
            model.objective_direction = 'max'
            f_max = model.slim_optimize()
            results[rid] = {"minimum": f_min, "maximum": f_max}
            if (i + 1) % 100 == 0:
                print(f"  Processed {i+1}/{len(rxn_map)}...")

    return pd.DataFrame(results).T

"""Set-up Per-Sample"""

metadata_subset = gem_data["metadata"]
nmr_subset      = gem_data["nmr"]


# NMR -> flux scale factor, calibrated on the glucose mean across ALL
# 6 samples (not High/Low specific -- this is a single global
# calibration constant, not part of the pooled comparison)
TARGET_GLUCOSE_FLUX_BY_CT = {
    "KER1":   1.0,
    "T CELL": 10.0,   # higher baseline glycolytic capacity of activated T cells
}
nmr_all_mean = nmr_subset.mean()

SCALE_BY_CT = {}
for ct, target in TARGET_GLUCOSE_FLUX_BY_CT.items():
    glucose_nmr_mean = float(nmr_all_mean["Glucose"])  # nmr_all_mean already computed earlier
    SCALE_BY_CT[ct] = target / glucose_nmr_mean if glucose_nmr_mean > 0 else 0.01
    print(f"[{ct}] SCALE = {SCALE_BY_CT[ct]:.6f} (target glucose flux = {target})")

"""Per-Sample Models"""

# ======================================================================
# RESTRUCTURED SECTION 2: per-sample, per-cell-type multi-omic integration
# ======================================================================

import cobra
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from cobra.flux_analysis import pfba

PATIENT_COL = "eg_id"
CELL_TYPES  = ["KER1", "T CELL"]
BIOMASS_ID  = "MAR13082"
MIN_CELLS   = 20

metadata_subset = gem_data["metadata"]
nmr_subset      = gem_data["nmr"]

assert PATIENT_COL in metadata_subset.columns, (
    f"metadata_subset has no '{PATIENT_COL}' column."
)

sample_ids  = list(common_ids)
sample_info = metadata_subset.loc[sample_ids, ["SA_status", PATIENT_COL]].copy()
print("Samples going into per-sample model building:")
print(sample_info)

# ----------------------------------------------------------------
# Per-sample, per-cell-type expression -> Ensembl -> GIMME weights,
# skipping any (sample, cell type) combo below MIN_CELLS
# ----------------------------------------------------------------
mean_expr_by_sample_ens = {}   # [ct][sid]
weights_by_sample       = {}   # [ct][sid]
threshold_by_sample     = {}   # [ct][sid]

for ct in CELL_TYPES:
    mean_expr_by_sample_ens[ct] = {}
    weights_by_sample[ct] = {}
    threshold_by_sample[ct] = {}
    counts = gem_data["cell_counts_by_sample"][ct]

    for sid in sample_ids:
        n_cells = counts.loc[sid, "n_cells"]
        if n_cells < MIN_CELLS:
            print(f"Skipping {sid} for {ct}: only {n_cells} cells (< {MIN_CELLS})")
            continue

        expr_series = convert_expr_to_ensembl(
            gem_data["mean_expr_by_sample"][ct][[sid]].iloc[:, 0], symbol_to_ens
        )
        mean_expr_by_sample_ens[ct][sid] = expr_series

        w, thresh = build_reaction_weights(model, expr_series)
        weights_by_sample[ct][sid] = w
        threshold_by_sample[ct][sid] = thresh
        print(f"{sid} [{ct}]: threshold={thresh:.4f}, "
              f"penalised={sum(1 for v in w.values() if v > 0)}/{len(w)}")

# ----------------------------------------------------------------
# Per-sample, per-cell-type constrained models
# (metabolite/pH constraints don't depend on cell type -- only the
# GIMME weights above do -- but a fresh model is built per combo to
# avoid cross-contamination from later GIMME runs)
# ----------------------------------------------------------------
def build_sample_model(sid, ct):
    sa_status = sample_info.loc[sid, "SA_status"]
    nmr_row   = nmr_subset.loc[sid]
    m = apply_metabolite_constraints(
        model, nmr_row, exchange_map, METABOLITE_DIRECTION,
        scale=SCALE_BY_CT[ct]
    )
    m = apply_environmental_context(m, sa_status.lower())
    return m

sample_models = {}
for ct in CELL_TYPES:
    sample_models[ct] = {}
    for sid in weights_by_sample[ct].keys():
        m = build_sample_model(sid, ct)          # now passes ct
        sample_models[ct][sid] = m
        sol = m.optimize()
        bio = sol.objective_value if sol.status == "optimal" else 0.0
        print(f"{sid} [{ct}] ({sample_info.loc[sid,'SA_status']}, "
              f"{sample_info.loc[sid, PATIENT_COL]}): status={sol.status}, biomass={bio:.4f}")
        if sol.status != "optimal":
            print(f"  WARNING: {sid} [{ct}] infeasible after constraints.")

# ----------------------------------------------------------------
# Metabolic task validation, per sample, per cell type
# ----------------------------------------------------------------
all_passed = True
for ct in CELL_TYPES:
    for sid in sample_models[ct].keys():
        label = f"{sid} [{ct}] ({sample_info.loc[sid,'SA_status']}, {sample_info.loc[sid, PATIENT_COL]})"
        passed = run_metabolic_tasks(sample_models[ct][sid], label, METABOLIC_TASKS_BY_CT[ct])  # now passes ct's task list
        all_passed = all_passed and passed

if not all_passed:
    print("\nWARNING: one or more samples failed task validation. "
          "Resolve before trusting GIMME/pFBA results for those samples.")

import ast
import numpy as np
from cobra.flux_analysis import pfba

# ----------------------------------------------------------------
# E-Flux: scale each reaction's bounds by its (GPR-resolved) expression.
# High expression -> wide bounds; low expression -> narrow (but never
# hard-zero) bounds. Never imposes a separate minimisation objective,
# so it does not conflict with the biomass lock (unlike GIMME).
# ----------------------------------------------------------------

def reaction_expression(model, expr_series):
    """GPR-resolved expression per reaction (reuses evaluate_gpr).
    Returns dict {rxn_id: expr_value or None}."""
    expr_lookup = expr_series.to_dict()
    rxn_expr = {}
    for rxn in model.reactions:
        if not rxn.gene_reaction_rule or rxn.gene_reaction_rule.strip() == "":
            rxn_expr[rxn.id] = None          # no GPR -> leave bounds untouched
            continue
        try:
            tree = ast.parse(rxn.gene_reaction_rule, mode="eval")
            rxn_expr[rxn.id] = evaluate_gpr(tree, expr_lookup)
        except Exception:
            rxn_expr[rxn.id] = None
    return rxn_expr


def apply_eflux(m, expr_series, biomass_id, protected_ids=None):
    """Scale internal reaction bounds by normalised expression.

    - Reactions with no GPR or unmapped genes: bounds left as-is.
    - Reactions with expression: bounds scaled to expr/max_expr * original.
    - Exchange/boundary reactions and the biomass reaction are NOT scaled
      (their bounds come from NMR/pH constraints and the growth lock).
    """
    if protected_ids is None:
        protected_ids = set()

    rxn_expr = reaction_expression(m, expr_series)
    vals = [v for v in rxn_expr.values() if v is not None and v > 0]
    if not vals:
        return m, 0
    max_expr = max(vals)

    boundary_ids = {r.id for r in m.boundary}
    n_scaled = 0

    for rxn in m.reactions:
        if rxn.id in boundary_ids or rxn.id == biomass_id or rxn.id in protected_ids:
            continue
        e = rxn_expr[rxn.id]
        if e is None:
            continue                          # untouched: no expression info
        scale = max(e, 0.0) / max_expr        # in [0, 1]
        # Scale bounds toward zero by the expression fraction, but keep a
        # small floor so nothing is fully blocked (preserves feasibility).
        floor = 1e-3
        factor = max(scale, floor)
        if rxn.upper_bound > 0:
            rxn.upper_bound = rxn.upper_bound * factor
        if rxn.lower_bound < 0:
            rxn.lower_bound = rxn.lower_bound * factor
        n_scaled += 1

    return m, n_scaled

# ----------------------------------------------------------------
# Compute shared growth rate from E-Flux-SCALED models, so the locked
# target never exceeds what the expression-constrained network can reach
# ----------------------------------------------------------------
shared_growth_rate = {}

for ct in CELL_TYPES:
    scaled_max_biomass = {}
    for sid in sample_models[ct]:
        m = sample_models[ct][sid].copy()
        m, _ = apply_eflux(m, mean_expr_by_sample_ens[ct][sid], biomass_id=BIOMASS_ID)
        scaled_max_biomass[sid] = m.slim_optimize()
    shared_growth_rate[ct] = min(scaled_max_biomass.values()) * 0.7
    print(f"[{ct}] Scaled max biomass per sample:", {k: round(v, 3) for k, v in scaled_max_biomass.items()})
    print(f"[{ct}] Shared growth rate (70% of scaled min): {shared_growth_rate[ct]:.4f}")

# ----------------------------------------------------------------
# Per-sample, per-cell-type E-Flux + pFBA
# ----------------------------------------------------------------
eflux_solutions = {}   # keep the same downstream variable name your
                       # flux-matrix code reads, OR alias below
gimme_solutions = {}   # <-- alias so downstream code works unchanged

for ct in CELL_TYPES:
    gimme_solutions[ct] = {}
    for sid in sample_models[ct]:
        m = sample_models[ct][sid].copy()

        # 1. Apply E-Flux expression scaling to internal reactions
        m, n_scaled = apply_eflux(
            m,
            mean_expr_by_sample_ens[ct][sid],
            biomass_id=BIOMASS_ID,
        )

        # 2. Lock biomass at the shared growth rate (same as before)
        biomass_rxn = m.reactions.get_by_id(BIOMASS_ID)
        biomass_rxn.lower_bound = shared_growth_rate[ct]
        biomass_rxn.upper_bound = shared_growth_rate[ct]

        # 3. pFBA for the parsimonious flux distribution
        try:
            sol = pfba(m)
            gimme_solutions[ct][sid] = sol
            print(f"{sid} [{ct}]: OK (scaled {n_scaled} reactions, "
                  f"pFBA obj={sol.objective_value:.4f})")
        except Exception as e:
            gimme_solutions[ct][sid] = None
            print(f"{sid} [{ct}]: FAILED ({e})")
# ----------------------------------------------------------------
# ----------------------------------------------------------------
# Assemble a tidy flux matrix per cell type: reactions x samples
# ----------------------------------------------------------------
flux_matrix = {}
summary = {}

for ct in CELL_TYPES:
    sids_ct = [sid for sid in gimme_solutions[ct] if gimme_solutions[ct][sid] is not None]
    skipped = [sid for sid in gimme_solutions[ct] if gimme_solutions[ct][sid] is None]
    if skipped:
        print(f"[{ct}] Skipping {skipped} from flux_matrix -- GIMME solve failed.")

    fm = pd.DataFrame({sid: gimme_solutions[ct][sid].fluxes for sid in sids_ct})
    fm.columns = pd.MultiIndex.from_tuples(
        [(sid, sample_info.loc[sid, "SA_status"], sample_info.loc[sid, PATIENT_COL])
         for sid in sids_ct],
        names=["sample_id", "SA_status", PATIENT_COL],
    )
    flux_matrix[ct] = fm
    print(f"[{ct}] fm shape: {fm.shape}")

    high_cols = [c for c in fm.columns if c[1] == "High"]
    low_cols  = [c for c in fm.columns if c[1] == "Low"]
    s = pd.DataFrame({
        "low_mean":  fm[low_cols].mean(axis=1)  if low_cols  else np.nan,
        "high_mean": fm[high_cols].mean(axis=1) if high_cols else np.nan,
    })
    s["group_diff"] = s["high_mean"] - s["low_mean"]
    print(f"[{ct}] high_cols: {high_cols}")
    print(f"[{ct}] low_cols: {low_cols}")
    summary[ct] = s
# ----------------------------------------------------------------
# Patient-consistency check, per cell type
# ----------------------------------------------------------------
for ct in CELL_TYPES:
    fm = flux_matrix[ct]
    high_cols = [c for c in fm.columns if c[1] == "High"]
    if not high_cols:
        continue

    high_patients = sample_info.loc[[c[0] for c in high_cols], PATIENT_COL].unique()
    print(f"\n[{ct}] High-group patients: {list(high_patients)}")

    per_patient_high_means = {}
    for p in high_patients:
        cols_p = [c for c in high_cols if c[2] == p]
        if cols_p:
            per_patient_high_means[p] = fm[cols_p].mean(axis=1)

    if len(per_patient_high_means) == 2:
        patient_agreement = pd.DataFrame(per_patient_high_means)
        patient_agreement["abs_disagreement"] = (
            patient_agreement.iloc[:, 0] - patient_agreement.iloc[:, 1]
        ).abs()
        print(f"[{ct}] Top reactions where the two High-group patients disagree most:")
        print(patient_agreement.sort_values("abs_disagreement", ascending=False).head(15))

    corr = fm.corr()
    print(f"\n[{ct}] Sample-sample flux correlation "
          f"(check whether clustering follows SA_status or patient):")
    print(corr.round(3))

    if ct in summary and not summary[ct]["group_diff"].isna().all():
        top_reactions = summary[ct]["group_diff"].abs().sort_values(ascending=False).head(20).index
        plot_df = fm.loc[top_reactions]
        plot_df.columns = [f"{sid}\n{status}/{pat}" for sid, status, pat in plot_df.columns]

        plt.figure(figsize=(10, 12))
        plt.imshow(plot_df.values, aspect="auto", cmap="RdBu_r")
        plt.colorbar(label="flux")
        plt.yticks(range(len(plot_df.index)), plot_df.index)
        plt.xticks(range(len(plot_df.columns)), plot_df.columns, rotation=45, ha="right")
        plt.title(f"[{ct}] Per-sample flux, top 20 reactions by |High mean - Low mean|")
        plt.tight_layout()
        plt.show()

# ======================================================================
# NOTE on FVA: full FVA per sample per cell type is expensive (up to
# 12x your original single-model FVA runtime). Restrict it to
# top_reactions per cell type, or keep full FVA only on the old


# pooled model_high_KER1/model_low_KER1 as a sanity check.

for ct in CELL_TYPES:
    final_samples = list(flux_matrix[ct].columns.get_level_values("sample_id").unique())
    print(f"[{ct}] Final samples in flux_matrix (n={len(final_samples)}): {final_samples}")
    # ==========

"""Saving"""

# ======================================================================
# EXPORT: per-sample, per-cell-type results to disk
#
# Mirrors the old code's habit of saving everything to project_folder,
# but keeps these files clearly separate and labelled so they are never
# confused with the old pooled (model_high_KER1/model_low_KER1) results
# that the "Visualisation and Analysis" section currently reads from.
#
# Add this at the end of the per-sample block, after the patient-
# consistency loop. Reuses `project_folder`, already defined earlier
# in the notebook by the old code's FVA-saving step.
# ======================================================================

import os

per_sample_dir = f"{project_folder}PerSample_PerCellType/"
os.makedirs(per_sample_dir, exist_ok=True)

patient_agreement_by_ct = {}  # populated below, also kept for in-notebook use

for ct in CELL_TYPES:
    if ct not in flux_matrix:
        continue

    fm = flux_matrix[ct]
    ct_tag = ct.replace(" ", "")

    # ------------------------------------------------------------
    # 1. Full per-sample flux matrix (reactions x samples), with
    #    sample/group/patient as flat columns rather than a
    #    MultiIndex, so it's a normal CSV
    # ------------------------------------------------------------
    fm_flat = fm.copy()
    fm_flat.columns = [f"{sid}__{status}__{pat}" for sid, status, pat in fm.columns]
    fm_flat.to_csv(f"{per_sample_dir}FluxMatrix_{ct_tag}.csv")

    # ------------------------------------------------------------
    # 2. Summary table (high_mean, low_mean, group_diff) with
    #    reaction metadata attached, same style as the old
    #    fva_export table, so it can be visualised the same way
    #    later if you choose route B
    # ------------------------------------------------------------
    s = summary[ct].copy()
    if ct in clean_models and len(clean_models[ct]) > 0:
        any_model = next(iter(clean_models[ct].values()))
        rxn_meta = {r.id: (r.name, r.subsystem) for r in any_model.reactions}
        s[["name", "subsystem"]] = s.index.to_series().apply(
            lambda x: pd.Series(rxn_meta.get(x, ("Unknown", "Unknown")))
        )
    s.to_csv(f"{per_sample_dir}Summary_{ct_tag}.csv")

    # ------------------------------------------------------------
    # 3. Patient-agreement table for the High group (if computed)
    # ------------------------------------------------------------
    high_cols = [c for c in fm.columns if c[1] == "High"]
    if high_cols:
        high_patients = sample_info.loc[[c[0] for c in high_cols], PATIENT_COL].unique()
        per_patient_high_means = {}
        for p in high_patients:
            cols_p = [c for c in high_cols if c[2] == p]
            if cols_p:
                per_patient_high_means[p] = fm[cols_p].mean(axis=1)

        if len(per_patient_high_means) == 2:
            pa = pd.DataFrame(per_patient_high_means)
            pa["abs_disagreement"] = (pa.iloc[:, 0] - pa.iloc[:, 1]).abs()
            pa = pa.sort_values("abs_disagreement", ascending=False)
            pa.to_csv(f"{per_sample_dir}PatientAgreement_High_{ct_tag}.csv")
            patient_agreement_by_ct[ct] = pa

    # ------------------------------------------------------------
    # 4. Sample-sample flux correlation matrix
    # ------------------------------------------------------------
    fm.corr().to_csv(f"{per_sample_dir}SampleCorrelation_{ct_tag}.csv")

    print(f"[{ct}] Saved FluxMatrix, Summary, "
          f"{'PatientAgreement, ' if ct in patient_agreement_by_ct else ''}"
          f"and SampleCorrelation to {per_sample_dir}")

print(f"\nAll per-sample, per-cell-type results saved under:\n  {per_sample_dir}")
print("These are kept separate from the old pooled-model results in "
      f"{project_folder} to avoid mixing the two analyses.")

"""Visualisation"""

# ======================================================================
# VISUALISE: per-sample, per-cell-type results
#
# Reads the CSVs saved by the export block, one set of plots per cell
# type. Deliberately keeps patient identity visible in every plot --
# unlike the old pooled heatmap, nothing here collapses to a single
# "High vs Low" number without showing where it came from.
# ======================================================================

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

plot_dir = f"{per_sample_dir}Plots/"
os.makedirs(plot_dir, exist_ok=True)

for ct in CELL_TYPES:
    ct_tag = ct.replace(" ", "")
    fm_path = f"{per_sample_dir}FluxMatrix_{ct_tag}.csv"
    if not os.path.exists(fm_path):
        print(f"Skipping {ct}: no FluxMatrix file found (likely excluded by MIN_CELLS).")
        continue

    fm = pd.read_csv(fm_path, index_col=0)
    # Columns were flattened as "sid__status__patient" -- parse back out
    col_info = [c.split("__") for c in fm.columns]
    sids      = [c[0] for c in col_info]
    statuses  = [c[1] for c in col_info]
    patients  = [c[2] for c in col_info]

    summary = pd.read_csv(f"{per_sample_dir}Summary_{ct_tag}.csv", index_col=0)

    # ------------------------------------------------------------
    # 1. Per-sample heatmap, top 20 reactions by |group_diff|
    #    Columns labelled sample/status/patient so the patient
    #    structure is visible directly in the figure, not hidden
    #    behind a 2-column High/Low average.
    # ------------------------------------------------------------
    top_reactions = summary["group_diff"].abs().sort_values(ascending=False).head(20).index
    top_reactions = [r for r in top_reactions if r in fm.index]

    plot_data = fm.loc[top_reactions]
    plot_labels = [f"{sid}\n{status} / {pat}" for sid, status, pat in zip(sids, statuses, patients)]

    if "name" in summary.columns:
        row_labels = [summary.loc[r, "name"] if r in summary.index and pd.notna(summary.loc[r, "name"])
                      else r for r in top_reactions]
    else:
        row_labels = top_reactions

    plot_log = np.sign(plot_data.values) * np.log1p(np.abs(plot_data.values))

    plt.figure(figsize=(max(8, len(plot_labels) * 1.1), 10))
    sns.heatmap(
        plot_log,
        xticklabels=plot_labels,
        yticklabels=row_labels,
        cmap="RdBu_r",
        center=0,
        cbar_kws={"label": "signed log1p(flux)"},
    )
    plt.title(f"[{ct}] Per-sample flux, top 20 reactions by |High mean - Low mean|\n"
              f"(columns are individual samples, not group averages)")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(f"{plot_dir}Heatmap_{ct_tag}.png", dpi=300)
    plt.show()

    # ------------------------------------------------------------
    # 2. Patient-agreement scatter: for the two High-group patients,
    #    do their per-reaction values agree? Points near the y=x
    #    line agree; points far from it are patient-driven, not
    #    abundance-driven, for that reaction.
    # ------------------------------------------------------------
    pa_path = f"{per_sample_dir}PatientAgreement_High_{ct_tag}.csv"
    if os.path.exists(pa_path):
        pa = pd.read_csv(pa_path, index_col=0)
        patient_cols = [c for c in pa.columns if c != "abs_disagreement"]

        if len(patient_cols) == 2:
            p1, p2 = patient_cols
            plt.figure(figsize=(7, 7))
            plt.scatter(pa[p1], pa[p2], alpha=0.4, s=15, color="grey", label="all reactions")

            top_disagree = pa.sort_values("abs_disagreement", ascending=False).head(10)
            plt.scatter(top_disagree[p1], top_disagree[p2], color="darkorange", s=40,
                        label="top 10 disagreeing reactions")

            lims = [min(pa[p1].min(), pa[p2].min()), max(pa[p1].max(), pa[p2].max())]
            plt.plot(lims, lims, linestyle="--", color="black", linewidth=1, label="perfect agreement (y=x)")

            plt.xlabel(f"Flux, patient {p1}")
            plt.ylabel(f"Flux, patient {p2}")
            plt.title(f"[{ct}] Do the two 'High' patients agree?\n"
                      f"Points near the line = abundance-consistent; "
                      f"far from it = patient-driven")
            plt.legend(fontsize=8)
            plt.tight_layout()
            plt.savefig(f"{plot_dir}PatientAgreement_{ct_tag}.png", dpi=300)
            plt.show()

    # ------------------------------------------------------------
    # 3. Sample-sample correlation clustermap: does clustering
    #    follow SA_status or patient identity?
    # ------------------------------------------------------------
    corr_path = f"{per_sample_dir}SampleCorrelation_{ct_tag}.csv"
    if os.path.exists(corr_path):
        corr = pd.read_csv(corr_path, index_col=0)
        corr.columns = plot_labels
        corr.index = plot_labels

        g = sns.clustermap(
            corr, cmap="vlag", center=0, figsize=(8, 8),
            annot=True, fmt=".2f", annot_kws={"size": 7},
        )
        g.fig.suptitle(f"[{ct}] Sample-sample flux correlation\n"
                        f"(check: does clustering follow status or patient?)",
                        y=1.02)
        g.savefig(f"{plot_dir}SampleCorrelation_{ct_tag}.png", dpi=300)
        plt.show()

    print(f"[{ct}] Saved plots to {plot_dir}")

print(f"\nAll per-sample, per-cell-type plots saved under:\n  {plot_dir}")
print("Reminder: with only 3 patients total, treat any visual pattern here "
      "as exploratory/hypothesis-generating, not confirmatory.")
